### ISSUE TITLE
Expression unit of TESLA output

### ISSUE THREAD

**Issue by nrosewick** [jianhuupenn/TESLA#12]
Hello,

I'm wondering what are the unit of the output of TESLA (i.e. enhanced_exp_adata data object) . Is there a way to get (pseudo-)raw counts from it ?

Thank you

**Comment by jianhuupenn** [comment]
Thanks for your interest in our method.
The imputation was conducted at the logged level to better preserve the spatial pattern than UMI count level.
You can use the exp function and round function to transform the value back to UMI, but it is not recommended, because there are no constraints on the total UMI count in a sample.
